stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - RaspberryPi
  script:
    - export JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-arm64
    - export PATH=$JAVA_HOME/bin:$PATH
    - ./gradlew quarkusBuild
  artifacts:
    paths:
      - build/UserServiceFARO-0.0.1-SNAPSHOT-runner.jar
    expire_in: 1 hour
  only:
    - main

deploy:
  stage: deploy
  tags:
    - RaspberryPi
  script:
    - echo "JWT_SECRET=${JWT_SECRET}" > .env
    - echo "QUARKUS_RABBITMQCLIENT_HOSTNAME=${QUARKUS_RABBITMQCLIENT_HOSTNAME}" >> .env
    - echo "QUARKUS_HTTP_PORT=8180" >> .env
    - docker compose -f docker-compose.arm.yml down
    - docker compose -f docker-compose.arm.yml up -d
  only:
    - main