stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - RaspberryPi
  script:
    - ./gradlew quarkusBuild
  artifacts:
    paths:
      - build/UserServiceFARO-0.0.1-SNAPSHOT-runner.jar
    expire_in: 1 hour
  only:
    - main

deploy:
  stage: deploy
  tags:
    - RaspberryPi
  script:
    # genera il .env con i valori corretti per Linux / Raspberry Pi
    - echo "JWT_SECRET=${JWT_SECRET}" > .env
    - echo "QUARKUS_RABBITMQCLIENT_HOSTNAME=${QUARKUS_RABBITMQCLIENT_HOSTNAME}" >> .env
    - echo "QUARKUS_HTTP_PORT=8180" >> .env
    # riavvia il container con il JAR aggiornato
    - docker compose -f docker-compose.arm.yml down
    - docker compose -f docker-compose.arm.yml up -d
  only:
    - main