services:

  RabbitMQFARO:
    image: rabbitmq:3.12-management
    platform: linux/arm64
    container_name: RabbitMQFARO
    ports:
      - "5672:5672"
      - "15672:15672"    # Management UI — http://<ip-raspberry>:15672  (FARO / FARO)
      - "15674:15674"    # WebSocket STOMP — app mobile
    environment:
      RABBITMQ_DEFAULT_USER: FARO
      RABBITMQ_DEFAULT_PASS: FARO
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_web_stomp && rabbitmq-server"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - faro-net

  UserMongoFARO:
    image: mongo:5.0
    platform: linux/arm64
    container_name: UserMongoFARO
    ports:
      - "27017:27017"
    volumes:
      - user-mongo-data:/data/db
    restart: unless-stopped
    networks:
      - faro-net

  MongoExpressFARO:
    image: mongo-express:1.0.0-alpha
    platform: linux/arm64
    container_name: MongoExpressFARO
    ports:
      - "8280:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: UserMongoFARO
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: FARO
      ME_CONFIG_BASICAUTH_PASSWORD: FARO
    depends_on:
      - UserMongoFARO
    restart: unless-stopped
    networks:
      - faro-net

  UserServiceFARO:
    image: eclipse-temurin:21-jre
    platform: linux/arm64
    container_name: UserServiceFARO
    ports:
      - "8180:8180"
      - "8100:8100"
    expose:
      - "8100"
    depends_on:
      - UserMongoFARO
      - RabbitMQFARO
    networks:
      - faro-net
    volumes:
      - ./build/UserServiceFARO-0.0.1-SNAPSHOT-runner.jar:/app/app.jar
    working_dir: /app
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8100 -jar /app/app.jar

volumes:
  user-mongo-data:
  rabbitmq-data:

networks:
  faro-net:
    external: true