quarkus.application.name=UserServiceFARO
quarkus.http.port=8090

# Security
jwt.secret=${JWT_SECRET:dev-secret-insecure-do-not-use-in-production}

# MongoDB
quarkus.mongodb.connection-string=mongodb://UserMongoFARO:27017
quarkus.mongodb.database=UserDB

# RabbitMQ
quarkus.rabbitmqclient.hostname=100.68.126.103
quarkus.rabbitmqclient.port=5672
quarkus.rabbitmqclient.username=FARO
quarkus.rabbitmqclient.password=FARO

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=*

# Autorizzazione per path
quarkus.http.auth.permission.public.paths=/api/authenticate/*,/api/registration/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.package.jar.type=uber-jar

